services:
  - type: web
    name: talk-with-friend-backend
    env: node
    plan: free
    rootDir: chat-app
    buildCommand: "cd chat-app && npm install"
    startCommand: "cd chat-app && npm run server"
    memoryMB: 512
    healthCheckPath: "/"
    envVars:
      - key: FRONTEND_URL
        value: "https://<your-frontend-url>"

  - type: static
    name: talk-with-friend-frontend
    env: static
    plan: free
    buildCommand: "cd chat-app/frontend && npm install --legacy-peer-deps && npm run build"
    publishPath: "chat-app/frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://<your-backend-url>"
