services:
  - type: web
    name: talk-with-friend-backend
    env: node
    plan: free
    rootDir: chat-app
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://alikasif9910_db_user:bAA2kTANbh09hDVw@cluster1.hbx7m0y.mongodb.net/chat-app?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: 466b34083ee6a60cd2a6cd023e81c3e42a83d43f3199c4be1330eeed5108fcfc812ab8a10742fa3e08e51fd1a0d403f537cbf32dadf62c427c6ca7e72ba0f7c6
